const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="curzonoderneisse@gmail.com"
global.location="Kolkata,India."


global.mongodb= process.env.MONGODB_URI || "mongodb://ufcngvivxrpkob45rmb0:sCyTB75IotGZTepszZR@bvm3mzejjuoe1qxjrvm1-mongodb.services.clever-cloud.com:2843/bvm3mzejjuoe1qxjrvm1"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Africa/Abidjan";
global.github=process.env.GITHUB|| "https://wa.me/message/K6OVW2JLF6DTI1";
global.gurl  =process.env.GURL  || "https://wa.me/message/K6OVW2JLF6DTI1";
global.website=process.env.GURL || "https://wa.me/message/K6OVW2JLF6DTI1" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/3d6ae74a9d7c125ec9df8.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "`𝖋𝖎𝖑𝖊 𝖌𝖊𝖓𝖊𝖗𝖆𝖙𝖊𝖉 𝖇𝖞 Ittou Rasetsu]`" 


global.devs = "919064560840" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "224620780851,22891442720,237655086741";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "224620780851";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "true" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https://wallpapercave.com/wp/wp11261224.jpg" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "unavailable" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_04_54_11_25_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDgsXG4gICAgICAgIDIxOCxcbiAgICAgICAgNzIsXG4gICAgICAgIDcyLFxuICAgICAgICAxNjAsXG4gICAgICAgIDUzLFxuICAgICAgICAyMCxcbiAgICAgICAgMjQ3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDQwLFxuICAgICAgICAyNDksXG4gICAgICAgIDcyLFxuICAgICAgICAxODMsXG4gICAgICAgIDI4LFxuICAgICAgICAxNTEsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMTc1LFxuICAgICAgICAxOTgsXG4gICAgICAgIDU5LFxuICAgICAgICAxNzYsXG4gICAgICAgIDI4LFxuICAgICAgICAxMTgsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTczLFxuICAgICAgICA5MyxcbiAgICAgICAgMzMsXG4gICAgICAgIDE0NyxcbiAgICAgICAgOSxcbiAgICAgICAgNzAsXG4gICAgICAgIDM2LFxuICAgICAgICAyMzEsXG4gICAgICAgIDEwNFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNTIsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjQ4LFxuICAgICAgICAyMDcsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMDcsXG4gICAgICAgIDc3LFxuICAgICAgICAxMjQsXG4gICAgICAgIDI2LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjI2LFxuICAgICAgICA5OCxcbiAgICAgICAgMTIzLFxuICAgICAgICAxNjAsXG4gICAgICAgIDAsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTUxLFxuICAgICAgICAxOTEsXG4gICAgICAgIDgzLFxuICAgICAgICAxNzMsXG4gICAgICAgIDczLFxuICAgICAgICA4MyxcbiAgICAgICAgMTA2LFxuICAgICAgICAxNzgsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMzksXG4gICAgICAgIDk3LFxuICAgICAgICAxMzcsXG4gICAgICAgIDk4LFxuICAgICAgICAxMTRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjksXG4gICAgICAgIDIxNixcbiAgICAgICAgOSxcbiAgICAgICAgOTEsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTY0LFxuICAgICAgICAxMTksXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTk0LFxuICAgICAgICA5OCxcbiAgICAgICAgNDQsXG4gICAgICAgIDE3OSxcbiAgICAgICAgOTgsXG4gICAgICAgIDIyLFxuICAgICAgICA3OSxcbiAgICAgICAgODQsXG4gICAgICAgIDE5NixcbiAgICAgICAgMjMsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMjA5LFxuICAgICAgICAyNTAsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTA0LFxuICAgICAgICAxODMsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTM0LFxuICAgICAgICAxMTEsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMjI3LFxuICAgICAgICAyMTYsXG4gICAgICAgIDEyNVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzcsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMSxcbiAgICAgICAgMTc1LFxuICAgICAgICA2MixcbiAgICAgICAgMTcyLFxuICAgICAgICAxNjIsXG4gICAgICAgIDU0LFxuICAgICAgICAxMTQsXG4gICAgICAgIDU1LFxuICAgICAgICAxMjMsXG4gICAgICAgIDEwNixcbiAgICAgICAgOTgsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMjA4LFxuICAgICAgICA5MCxcbiAgICAgICAgMTAyLFxuICAgICAgICA4OCxcbiAgICAgICAgMTU0LFxuICAgICAgICAxMSxcbiAgICAgICAgMjMsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTkwLFxuICAgICAgICA4NSxcbiAgICAgICAgMixcbiAgICAgICAgNTYsXG4gICAgICAgIDI0LFxuICAgICAgICA5MixcbiAgICAgICAgMCxcbiAgICAgICAgMTg1LFxuICAgICAgICAxMzEsXG4gICAgICAgIDQ2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMzIsXG4gICAgICAgIDkyLFxuICAgICAgICAxMDAsXG4gICAgICAgIDE1MyxcbiAgICAgICAgNDYsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMjEyLFxuICAgICAgICA1MCxcbiAgICAgICAgMjE1LFxuICAgICAgICA5MSxcbiAgICAgICAgNDUsXG4gICAgICAgIDExMixcbiAgICAgICAgMTAyLFxuICAgICAgICAxMTAsXG4gICAgICAgIDE5MCxcbiAgICAgICAgNTMsXG4gICAgICAgIDMzLFxuICAgICAgICAyNDgsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxNjAsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjQwLFxuICAgICAgICAxODcsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxNTMsXG4gICAgICAgIDYwLFxuICAgICAgICA0NCxcbiAgICAgICAgMjAsXG4gICAgICAgIDIzLFxuICAgICAgICA4OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzIsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjQyLFxuICAgICAgICAyMyxcbiAgICAgICAgNzksXG4gICAgICAgIDExMCxcbiAgICAgICAgMTE4LFxuICAgICAgICA0MSxcbiAgICAgICAgMjE2LFxuICAgICAgICA4NCxcbiAgICAgICAgMzEsXG4gICAgICAgIDM3LFxuICAgICAgICAyMyxcbiAgICAgICAgMTc3LFxuICAgICAgICAxNjMsXG4gICAgICAgIDQ2LFxuICAgICAgICA2OCxcbiAgICAgICAgMTA2LFxuICAgICAgICAxNjIsXG4gICAgICAgIDIxMCxcbiAgICAgICAgNTMsXG4gICAgICAgIDc1LFxuICAgICAgICAxMixcbiAgICAgICAgMTkxLFxuICAgICAgICAyMzgsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTI5LFxuICAgICAgICAyNDEsXG4gICAgICAgIDE3LFxuICAgICAgICAzLFxuICAgICAgICAxMjgsXG4gICAgICAgIDEwNVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgNCxcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgMTQ0LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgMjE3LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDM5LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAzMyxcbiAgICAgICAgICA4NFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICA0LFxuICAgICAgICAgIDY5LFxuICAgICAgICAgIDU1LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAxOTQsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAzNixcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICAxMjRcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAzOCxcbiAgICAgICAgMjIyLFxuICAgICAgICAxNyxcbiAgICAgICAgNjYsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTkzLFxuICAgICAgICA2MixcbiAgICAgICAgMzksXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTkzLFxuICAgICAgICAxNyxcbiAgICAgICAgNSxcbiAgICAgICAgMTc5LFxuICAgICAgICAxODAsXG4gICAgICAgIDE5LFxuICAgICAgICAxMjEsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjI5LFxuICAgICAgICAyNDIsXG4gICAgICAgIDk4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDM0LFxuICAgICAgICAyMDksXG4gICAgICAgIDE4LFxuICAgICAgICA4MixcbiAgICAgICAgMTYxLFxuICAgICAgICA2MSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxNjEsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMTMsXG4gICAgICAgIDI5LFxuICAgICAgICA4OSxcbiAgICAgICAgMjMzLFxuICAgICAgICAyMDksXG4gICAgICAgIDU2LFxuICAgICAgICAyNTIsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMTkyLFxuICAgICAgICAxMTYsXG4gICAgICAgIDQ4LFxuICAgICAgICAyMDYsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMjE1LFxuICAgICAgICAyMTEsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMjAyLFxuICAgICAgICAzNixcbiAgICAgICAgMTQ3LFxuICAgICAgICAxMTksXG4gICAgICAgIDEyOCxcbiAgICAgICAgODAsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTE4LFxuICAgICAgICA0MixcbiAgICAgICAgMTE5LFxuICAgICAgICAxMzUsXG4gICAgICAgIDIyLFxuICAgICAgICA2MSxcbiAgICAgICAgMTg2LFxuICAgICAgICAxMzMsXG4gICAgICAgIDE4MixcbiAgICAgICAgODAsXG4gICAgICAgIDEzMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogOTIsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwibWd1QmZXaEZhSWd3TSt6cFRuZ2g4L0dLZXV6a1ZVUUpSNEM4c0JoLzQ4cz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyMjQ2MjA3ODA4NTFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjM3NkRFRjRENUM2OTQ3MkREMTZDRkJENjI3QzZEMTFCXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTczMjUxMDQ1NFxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjIyNDYyMDc4MDg1MUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQ0NDODNBMzBCQTBBNDEzRkQyQkI5RTcyQTkwRUM3QkJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzMyNTEwNDU0XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIjV3OE1EeThXUld5c1pQZWZvM0RRb3dcIixcbiAgXCJwaG9uZUlkXCI6IFwiN2ZhMDg1MDItNjc0MC00NTNkLTllYzQtZjg0OTZiNmUzMDFlXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDkwLFxuICAgICAgMTA1LFxuICAgICAgMTUwLFxuICAgICAgMjE1LFxuICAgICAgMTU1LFxuICAgICAgMTQyLFxuICAgICAgMTIxLFxuICAgICAgMjE5LFxuICAgICAgNzEsXG4gICAgICA3OCxcbiAgICAgIDUyLFxuICAgICAgMixcbiAgICAgIDEzMixcbiAgICAgIDM2LFxuICAgICAgMTA2LFxuICAgICAgNTEsXG4gICAgICAxNTMsXG4gICAgICAxNzAsXG4gICAgICAyMDgsXG4gICAgICAxMjRcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE5OSxcbiAgICAgIDEzNCxcbiAgICAgIDI1MSxcbiAgICAgIDE5NixcbiAgICAgIDE3NyxcbiAgICAgIDE3NSxcbiAgICAgIDk3LFxuICAgICAgMjMyLFxuICAgICAgMTU4LFxuICAgICAgMTQ0LFxuICAgICAgMTYwLFxuICAgICAgMTE3LFxuICAgICAgMjA0LFxuICAgICAgMjQzLFxuICAgICAgMTg5LFxuICAgICAgMjEzLFxuICAgICAgNDcsXG4gICAgICAxMzMsXG4gICAgICAxODMsXG4gICAgICAxMjJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNKbkJzTGtCRU8rRmtMb0dHQVVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjFzQ2M1UmZ1d3krKzgzbjduNzMvbHg1OHJzbWZ4WnlUTDFDeW5teFlQUXM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiOXJtcFpibGlCUFZ0Z2JwaW12bDFHU214c0dsbHd2aU1FYlhRdjFqVXpuOVdBWDNtQ2tuZDhLTmR4RndaRFZCcUFIWDJ6WkZzdlJvdjJQRzRkbEV6Q2c9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiMVpER284bVRoM0p2YzRBOGxmYWdTTlJ5Q2pHR2puREY4akxxRUVvSWE2L1ByOFdWa0JmMDNuaHQ3S3N6OVVlTEJPMjNMRzVXeUFTNGc3bVQwT3NpZ3c9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMjQ2MjA3ODA4NTE6ODNAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjgzODg1MzU4NjEyNTA3OjgzQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIsmq4bSb4bSb4bSP4bScIMqA4bSAc+G0h+G0m3PhtJxcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIyNDYyMDc4MDg1MTo4M0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAyMzgsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgMTI0LFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDExXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MzI1MTA0NTEsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFGY0JcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUZjQi5qc29uIjogIntcImtleURhdGFcIjpcIkl1bkdvTlBWV0RnNVc0T09Ibnd2OVNtdzBaSEIxb3lSa09NMFBFc0tOd1U9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6Mzg4NzY3ODk2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFGY0MuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI3NmN1YmhZYnpzMTh5bU9ObG9hNnhndHRIQTIzdHNxc0o0K01uRWtGNVc0PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjM4ODc2Nzg5NixcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsMiwzXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFGY0QuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ3aXNmNTJtZ01aSW14V1QxUVZOUkJVS1p0cXNiOWtKOFkwMlV6dnVXaXJBPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjM4ODc2Nzg5NixcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzAsMiwzXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFGY0UuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJteENVUHVrbEhHRmpvbmtJbi83V2hSbGlUU1RNV3J0U1hqZUJqK1dKQ0xNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjM4ODc2Nzg5NixcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzAsMiwzXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFGY0YuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJMd2YwSzBUYUtuK2lzQTJJenVBd2Z6ZmFKYVd5OUwvTHRjOVlyY1BOZ1pNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjM4ODc2Nzg5NixcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzAsMl19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRmNHLmpzb24iOiAie1wia2V5RGF0YVwiOlwibTFIZXJ1YWVOQVdjRkFuSm1oektyZmtYTXFzemRDQmJ5TDhYR0pPTUh1QT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozODg3Njc4OTYsXCJjdXJyZW50SW5kZXhcIjo1LFwiZGV2aWNlSW5kZXhlc1wiOlswXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MzEwNzcwOTUyNzNcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFGY0guanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJZWEl2Nm5OU2J2V3lXQVd1Wk5xOFJUTHpROGhYU1RheXVTU3B6bGN1NWtVPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjM4ODc2Nzg5NyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRmNJLmpzb24iOiAie1wia2V5RGF0YVwiOlwiMmwvbGNPNjM0S05tSjA4bUtGemVCRzhFSTdrUStrYkdDSjRWUFFmL3R1VT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozODg3Njc4OTcsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsM119LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRmNKLmpzb24iOiAie1wia2V5RGF0YVwiOlwiMlpVRDNaa3FrWGNuaFlXT2tWLzVqN0FQNjZUbmxOaS9UQWxOaS8vanlxST1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjozODg3Njc4OTcsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDMsNF19LFwidGltZXN0YW1wXCI6XCIxNzMyNTEwNDQyMjU5XCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.0.1-developement-x",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ Valstrax-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • crimson valstrax』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "Crimson Valstrax",
  ownername:process.env.OWNER_NAME|| "Crimson[Valstrax]",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "GOJO"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
